name: fcm_push
description: A Dart interface to Firebase Cloud Messaging (FCM) for Android and iOS
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-fcm-push

version: 1.1.3

environment:
  sdk: '>=1.8.0 <2.0.0'

# Add the bin/packages.dart script to the scripts pub installs.
# Activate local repo:
#   pub global activate --source path .
#
executables:
  fcm-push:

dependencies:
  args: ^0.13.0
  yaml: ^2.1.0

  firebase: ^4.0.0

  validate: ^1.5.0

  tuple: ^1.0.0

  http_utils: ^1.4.0

  ansicolor: ^0.0.9

dev_dependencies:
  test: any
  grinder: any
  console_log_handler: any
