name: fcm_push
description: A Dart interface to Firebase Cloud Messaging (FCM) for Android and iOS
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-fcm-push

version: 1.0.0

environment:
  sdk: '>=1.0.0 <2.0.0'

# Add the bin/packages.dart script to the scripts pub installs.
# Activate local repo:
#   pub global activate --source path .
#
executables:
  fcm-push:

dependencies:
  logging: any
  logging_handlers: any
  console_log_handler: any

  validate: any

  args: any
  yaml: any

  firebase: ^3.0.0

  validate: any

  tuple: any

  http_utils: any

  yaml: ^2.1.0
  
  ansicolor: any

dev_dependencies:
  test: any
  grinder: any
